auth_system/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #import this

app_name = 'auth_system'


urlpatterns = [
    path('login_user/',views.login_user,name='login_user'),
    path('register_user/',views.register_user,name='register_user'),
    path('logout_user/',views.logout_user,name='logout_user'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_system/password_reset_done.html'), name='password_reset_done'),#second
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="auth_system/password_reset_confirm.html",success_url="/auth_system/login_user/"), name='password_reset_confirm'),#third
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth_system/password_reset_complete.html'), name='password_reset_complete'), #four

    path("password_reset", views.password_reset_request, name="password_reset")#first
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'


urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('<int:id>/del_contact_us/',views.del_contact_us, name="del_contact_us"),
    path('all_users',views.all_users,name='all_users'),
    path('bus_registration/',views.bus_registration,name='bus_registration'),
    path('add_bus_seat/',views.add_bus_seat,name='add_bus_seat'),
    path('<int:id>/del_bus/',views.del_bus, name="del_bus"),
    path('add_routes/',views.add_routes,name='add_routes'),
    path('add_address/',views.add_address,name='add_address'),
    path('add_schedules/',views.add_schedules,name='add_schedules'),
    path('add_special_tours/',views.add_special_tours,name='add_special_tours'),
    path('<int:id>/del_stours/',views.del_stours, name="del_stours"),
    path('<int:id>/stours_details/',views.stours_details, name="stours_details"),
    path('all_bookings/',views.all_bookings,name='all_bookings'),
    path('<int:sid>/<str:d>/ubb_details/',views.ubb_details,name='ubb_details'),
    path('tour_bookings/',views.tour_bookings,name='tour_bookings'),
    path('<int:id>/tb_details/',views.tb_details,name='tb_details'),
    path('top_5users/',views.top_5users,name='top_5users'),
    path('top_5destinations/',views.top_5destinations,name='top_5destinations'),
    path('all_users_report/',views.all_users_report,name='all_users_report'),
    path('top_tours_report/',views.top_tours_report,name='top_tours_report')
]

pacific/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),   # redirect to home page
    path('auth_system/',include('auth_system.urls')),
    path('manager/',include('manager.urls')),
    path('booking/',include('booking.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

root/urls.py
from django.urls import path
from . import views

app_name = 'root'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('about_us/',views.about_us,name='about_us'),
    path('mydashboard/',views.mydashboard,name='mydashboard'),
    path("search_bus/", views.search_bus, name="search_bus"),
    path('tours/',views.tours,name='tours'),
    path('daily_tours/',views.daily_tours,name='daily_tours'),
    path('offer_tours/',views.offer_tours,name='offer_tours'),
    path('<int:id>/tour_details/',views.tour_details,name='tour_details'),
    path('<int:id>/booking_details/',views.booking_details,name='booking_details'),
    path('<int:id>/tour_booking_details/',views.tour_booking_details,name='tour_booking_details'),
    path('userside_report/',views.userside_report,name='userside_report')
]

root/models.py

from django.utils import timezone
from django.db import models

# Create your models here.
class Mailbox(models.Model):
    name = models.CharField(max_length = 100)
    email_id = models.EmailField(max_length=150)
    subject = models.CharField(max_length = 150)
    message = models.TextField()
    contact = models.TextField(max_length=10)
    date = models.DateField(default=timezone.now)

class SearchBus(models.Model):
    from_d = models.CharField(max_length=50,blank=False,null=False)
    to_d = models.CharField(max_length=50,blank=False,null=False)
    date = models.DateField(default=timezone.now)

root/forms.py
from django import forms
from datetime import datetime
from root.models import Mailbox,SearchBus

class EmailForm(forms.ModelForm):
    class Meta:
        model = Mailbox
        fields = ['name','email_id','subject','message','contact']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your Name'}),
            'email_id': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your Email'}),
            'subject': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Subject'}),
            'message': forms.Textarea(attrs={'class':'form-control','placeholder':'Enter Your Message','type':'textarea','rows':50,'cols':15}),
            'contact': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your contact number'}),
        }

class search_busForm(forms.ModelForm):
    class Meta:
        model = SearchBus
        fields = ['from_d','to_d','date']
        widgets = {
            'from_d': forms.TextInput(attrs={'class':'form-control','placeholder':'From.....'}),
            'to_d': forms.TextInput(attrs={'class':'form-control','placeholder':'To....'}),
            'date': forms.NumberInput(attrs={'class': 'form-control date-pick','type':'date','min':datetime.now().date})
            
        }
   
                

root/views.py
from django.shortcuts import render,redirect
from .forms import EmailForm
from django.core.mail import EmailMessage
from django.conf import settings
from smtplib import SMTPAuthenticationError,SMTPException
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.template.loader import get_template,render_to_string
from .forms import search_busForm
from booking.models import Routes,Schedules,Special_Tours
from datetime import datetime
import socket
from booking.models import BusBookings,BusBookings_details,Seat,STourBooking,STourBooking_details
from auth_system.models import CustomUser
import razorpay
# Create your views here.
def index(request):

    tours_Data = Special_Tours.objects.filter(start_date__gte=datetime.now()).order_by('-id')

    context = {
        'form':search_busForm(),
        'tours_Data':tours_Data
    }
    return render(request,'root/index.html',context)

def search_bus(request):
    if request.method == 'POST':
        from_d = request.POST['from_d']
        to_d = request.POST['to_d']
        date_d = request.POST['date']

        date_obj = datetime.strptime(date_d, '%Y-%m-%d')
        day_date_obj = date_obj.strftime('%A')
        print(day_date_obj) # 2023-01-29
        #comments
        if not from_d :
            return redirect('root:index')
        else:

            lookups = Q(route_fk__origin_fk__city__icontains=from_d) & Q(route_fk__destination_fk__city__icontains=to_d) & Q(daysOfWeek__icontains=day_date_obj) 

            results = Schedules.objects.filter(lookups).distinct()
            
            if results.exists():

                context = {
                            'results': results,
                            'r_count': results.count(),
                            'date': date_d
                        }
                return render(request, 'root/search_bus.html', context)
            else:

                return render(request, 'root/search_not_found.html', {'from_d': from_d,'to_d':from_d})

    
    context = {
        
    }
    return render(request,'root/search_bus.html',context)
    

def contact_us(request):
    form = EmailForm()
    
    flag = ''
    try:
        # connect to the host -- tells us if the host is actually
        # reachable
        socket.create_connection(("1.1.1.1", 53))
        flag='net_on'
    except OSError:
        flag='net_off'

    if request.method == 'POST':
        form = EmailForm(request.POST)
        
        if form.is_valid():
            to_mail = form.cleaned_data.get('email_id')
            subject = form.cleaned_data.get('subject')
            message = form.cleaned_data.get('message')
            form.save()
            
            #reply as email to contected person
            e_tmp = 'root/email_thank_contactus.html'
            c = {'name':request.POST['name']}
            content = render_to_string(e_tmp,c)
            img_data = open('static/email_img/logo_2.png', 'rb').read()
            html_part = MIMEMultipart(_subtype='related')
            body = MIMEText(content, _subtype='html')
            html_part.attach(body)
            # Now create the MIME container for the image
            img = MIMEImage(img_data, 'png')
            img.add_header('Content-Id', '<myimage>')  # angle brackets are important
            img_data2 = open('static/email_img/logo_small.jpg', 'rb').read()
            img2 = MIMEImage(img_data2, 'jpg')
            img2.add_header('Content-Id', '<myimage2>')  # angle brackets are important
            # img.add_header("Content-Disposition", "inline", filename="myimage") # David Hess recommended this edit
            html_part.attach(img)
            html_part.attach(img2)
            msg = EmailMessage("Contact Us request received", None,  settings.EMAIL_HOST_USER,  [to_mail])
            msg.attach(html_part) # Attach the raw MIMEBase descendant. This is a public method on EmailMessage
            if flag == 'net_on':
                msg.send()
            else:
                print('network is not on')


            #?msg send to admin or manager's email id 
            e_tmp = 'root/email_received_contact.html'
            c = {
                'name':request.POST['name'],
                'msg':request.POST['message']
            }
            content = render_to_string(e_tmp,c)
            img_data = open('static/email_img/logo_2.png', 'rb').read()
            html_part = MIMEMultipart(_subtype='related')
            body = MIMEText(content, _subtype='html')
            html_part.attach(body)
            # Now create the MIME container for the image
            img = MIMEImage(img_data, 'png')
            img.add_header('Content-Id', '<myimage>')  # angle brackets are important
            img_data2 = open('static/email_img/logo_small.jpg', 'rb').read()
            img2 = MIMEImage(img_data2, 'jpg')
            img2.add_header('Content-Id', '<myimage2>')  # angle brackets are important
            # img.add_header("Content-Disposition", "inline", filename="myimage") # David Hess recommended this edit
            html_part.attach(img)
            html_part.attach(img2)
            msg = EmailMessage("Contact Us request received", None,  settings.EMAIL_HOST_USER,  [settings.EMAIL_HOST_USER])
            msg.attach(html_part) # Attach the raw MIMEBase descendant. This is a public method on EmailMessage
            if flag == 'net_on':
                msg.send()
            else:
                print('network is not on')
            
            return redirect('root:contact_us')
            
    context ={
        'form':form
    }
    return render(request,'root/contactus.html',context)


def about_us(request): 
    context = { 

    }
    return render(request,'root/about_us.html',context)


@login_required(login_url='auth_system:login_user') 
def mydashboard(request):
    current_date = datetime.now()
    user = CustomUser.objects.get(id=request.user.id)
    future_seat_booking = BusBookings.objects.filter(user_fk=user,travel_date__gte=current_date,paid=True)#,date__gte=current_date

    future_tour_bookings = STourBooking.objects.filter(user_fk=user,travel_date__gte=current_date,paid=True)

    context = {
        'up_seat_booking':future_seat_booking,
        'up_tour_booking':future_tour_bookings
    }
    return render(request,'root/mydashboard.html',context)


def tours(request):

    context = {
        'data':Special_Tours.objects.filter(start_date__gte=datetime.now())
    }
    return render(request,'root/tours.html',context)

def daily_tours(request):
    

    d = datetime.date(datetime.now())
    date_obj = datetime.strptime(str(d), '%Y-%m-%d')
    day_date_obj = date_obj.strftime('%A')
    print(day_date_obj)

    data = Schedules.objects.filter(daysOfWeek__icontains = day_date_obj)#
    context = {
        'results':data,
        'date':date_obj.strftime('%Y-%m-%d'),
        
    }
    return render(request,'root/daily_tour.html',context)

def offer_tours(request):
    context = {
        'data':Special_Tours.objects.filter(start_date__gte=datetime.now(),offer=True)
    }
    return render(request,'root/tours.html',context)

@login_required(login_url='auth_system:login_user')
def tour_details(request,id):
    data = Special_Tours.objects.get(id=id)
    
    
    seat_booked = STourBooking_details.objects.filter(stourbooking_fk__paid=True,stourbooking_fk__special_tours_fk=data)#,date=date_only.strftime('%Y/%m/%d')
    s_list = [i.seat_fk.seat_name for i in seat_booked]
    seats = Seat.objects.exclude(seat_name__in=s_list)
    available_seats = Seat.objects.filter(bus_fk=data.bus_fk_k,id__in=seats)

    user_id = CustomUser.objects.get(id=request.user.id)
    if request.method == 'POST':

        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        seat_list = request.POST.getlist('seats')

        t_price = len(seat_list) * int(data.price)
        if data.offer:
            minus = (t_price * 10) / 100
            t_price = t_price - int(minus)
        fname = first_name+' '+last_name

        STourBooking.objects.create(name=fname,total_price=t_price,user_fk=user_id,special_tours_fk=data,travel_date=data.start_date,)
        Latest_STourB = STourBooking.objects.latest('id')

        for i in seat_list:
            seat = Seat.objects.get(seat_name=i)

            STourBooking_details.objects.create(stourbooking_fk=Latest_STourB,seat_fk=seat,date=datetime.now())

        t_price= t_price*100
        client = razorpay.Client(auth=("rzp_test_susforIvG6nYky", "VUQ8dfvBSkVS9Lstz9r1pQ9r"))
        payment = client.order.create({'amount': t_price, 'currency': 'INR','payment_capture': '1'})

        Latest_STourB.razorpay_order_id = payment['id']
        Latest_STourB.save()
        return render(request, 'booking/razorpay_stours.html', {'payment': payment})


    context = {
        'data': data,
        'seats':available_seats
    }
    return render(request,'root/tour_details.html',context)

@login_required(login_url='auth_system:login_user')
def booking_details(request,id):
    data = BusBookings.objects.get(id=id)
    seats = BusBookings_details.objects.filter(busbookings_fk=data)
    cnt = seats.count()
    context={
        'data':data,
        'seats':seats,
        's_cnt':cnt
    }
    return render(request,'root/booking_details.html',context)

@login_required(login_url='auth_system:login_user')
def tour_booking_details(request,id):
    dis = ''
    data = STourBooking.objects.get(id=id)

templates/root/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pacific - Premium site template for city tours agencies, transfers and tickets.">
    <meta name="author" content="Ansonika">
    <title>Pacific Tours & Travels</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114"
        href="img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144"
        href="img/apple-touch-icon-144x144-precomposed.png">

    <!-- GOOGLE WEB FONT -->
    <link
        href="https://fonts.googleapis.com/css2?family=Gochi+Hand&amp;family=Montserrat:wght@300;400;500;600;700&amp;display=swap"
        rel="stylesheet">

    <!-- COMMON CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <link href="{% static '/css/vendors.css' %}" rel="stylesheet">

    <!-- ALTERNATIVE COLORS CSS -->
    <link href="#" id="colors" rel="stylesheet">
    
    {% block css %}
     <style>
        
     </style>   
    {% endblock css %}
        

</head>

<body>
    <div class="layer"></div>
    <!-- Header================================================== -->
    <header>
        <div id="top_line">
            <div class="container">
                <div class="row">
                    <div class="col-6"><i class="icon-phone"></i><strong>+96623 24834</strong></div>
                    <div class="col-6">
                        <ul id="top_links">

                            {% if user.is_authenticated %}
                            <li><a href="{% url 'auth_system:logout_user' %}" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'auth_system:login_user' %}" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Login</a></li>
                            <li><a href="{% url 'auth_system:register_user' %}" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Sign-in</a></li>
                            {% endif %}


                        </ul>
                    </div>
                </div><!-- End row -->
            </div><!-- End container-->
        </div><!-- End top line-->

        <div class="container">
            <div class="row">
                <div class="col-3">
                    <div id="logo_home">
                        <h1><a href="{% url 'root:index' %}" title="City tours travel template">Pacific Tours travel
                                template</a>
                        </h1>
                    </div>
                </div>
                <nav class="col-9">
                    <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu
                            mobile</span></a>
                    <div class="main-menu">
                        <div id="header_menu">
                            <img src="{% static 'img/logo_sticky.png' %}" width="160" height="34" alt="City tours">
                        </div>
                        <a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
                        <ul>
                            <li class="submenu">
                                <a href="{% url 'root:index' %}" class="show-submenu"  onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Home</a>
                            </li>&nbsp;&nbsp;&nbsp;
                            <li class="submenu">
                                <a href="{% url 'root:tours' %}" class="show-submenu" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Tours</a>
                            </li>&nbsp;&nbsp;&nbsp;
                            <li class="submenu">
                                <a href="{% url 'root:about_us' %}" class="show-submenu" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">About Us</a>
                            </li>&nbsp;&nbsp;&nbsp;
                            <li class="submenu">
                                <a href="{% url 'root:contact_us' %}" class="show-submenu" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">Contact Us</a>
                            </li>

                            {% if user.is_authenticated %}
                            <li class="submenu">
                                <a href="{% url 'root:mydashboard' %}" class="show-submenu" onMouseOver="this.style.color='black'" onMouseOut="this.style.color='white'">My Dashboard</a>
                            </li>
                            {% endif %}



                        </ul>

                    </div><!-- End main-menu -->
                    <!-- <ul id="top_tools">
                        <li>
                            <a href="javascript:void(0);" class="search-overlay-menu-btn"><i
                                    class="icon_search"></i></a>
                        </li>

                    </ul> -->
                </nav>
            </div>
        </div><!-- container -->
    </header><!-- End Header -->

    {% block body %}

    {% endblock body %}

    {% block section_slider %}

    {% endblock section_slider %}

    {% block section_special_offer %}

    {% endblock section_special_offer %}

    {% block section_top_th %}

    {% endblock section_top_th %}

    {% block section_plan %}

    {% endblock section_plan %}

    {% block section_blog %}

    {% endblock section_blog %}

    <footer class="revealed">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3>Need help?</h3>
                    <a href="tel://9662324834" id="phone">+96623 24734</a>
                    <a href="#" id="email_footer">pacifictourtravel23@gmail.com</a>
                </div>
                <div class="col-md-3">
                    <h3>About</h3>
                    <ul>
                        <li><a href="{% url 'root:about_us' %}">About us</a></li>
                        <li><a href="#">Tours</a></li>
                        <li><a href="{% url 'auth_system:login_user' %}">Login</a></li>
                        <li><a href="{% url 'auth_system:register_user' %}">Sign-in</a></li>
                        <li><a href="{% url 'root:contact_us' %}">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h3>Discover</h3>
                    <ul>
                        <li><a href="#">Community blog</a></li>
                        <li><a href="#">Tour guide</a></li>
                        <li><a href="#">Wishlist</a></li>
                        <li><a href="#">Gallery</a></li>
                    </ul>
                </div>
                <div class="col-md-2">
                    <h3>Pacific Tours & Travels</h3>
                    Our website is the perfect destination for anyone planning a tour or travel. Whether you're a solo
                    traveler, a couple, a family, or a group of friends, we have something for everyone.

                </div>
            </div><!-- End row -->
            <div class="row">
                <div class="col-md-12">
                    <div id="social_footer">
                        <ul>
                            <li><a href="#"><i class="icon-facebook"></i></a></li>
                            <li><a href="#"><i class="icon-google"></i></a></li>
                        </ul>
                        <p>© Pacific Tours & Travels 2023</p>
                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
    </footer><!-- End footer -->

    <div id="toTop"></div><!-- Back to top button -->

    <!-- Search Menu -->
    <div class="search-overlay-menu">
        <span class="search-overlay-close"><i class="icon_set_1_icon-77"></i></span>
        <form role="search" id="searchform" method="get">
            <input value="" name="q" type="text" placeholder="Search..." />
            <button type="submit"><i class="icon_set_1_icon-78"></i>
            </button>
        </form>
    </div><!-- End Search Menu -->



    <!-- Common scripts -->
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/common_scripts_min.js' %}"></script>
    <script src="{% static '/js/functions.js' %}"></script>

    <!-- NOTIFY BUBBLES  -->
    <script src="{% static '' %}"></script>

    <!-- SWITCHER  -->
    <script src="{% static 'js/switcher.js' %}"></script>

</body>

</html>

templates/root/section_plan.html
{% load static %}
<main>
    <div class="white_bg">
        <div class="container margin_60">
            <div class="main_title">
                <h2>Plan <span>Your Tour</span> Easly</h2>
                <p>
                    Book your tour today and experience the ultimate travel experience.
                </p>
            </div>
            <div class="row feature_home_2">
                <div class="col-md-4 text-center">
                    <img src="{% static 'img/adventure_icon_1.svg' %}" alt="" width="75" height="75">
                    <h3><span>H24</span> Support</h3>
                    <p>Our H24 support service is here to provide you with round-the-clock assistance whenever you need
                        it..</p>
                </div>
                <div class="col-md-4 text-center">
                    <img src="{% static 'img/adventure_icon_2.svg' %}" alt="" width="75" height="75">
                    <h3><span> Room and food</span> included</h3>
                    <p> Experience comfort and convenience on our tours, as we take care of your accommodation and meal
                        needs. Our carefully selected hotels offer comfortable rooms, ensuring you get a good night's
                        sleep after a day of exploring. .</p>
                </div>
                <div class="col-md-4 text-center">
                    <img src="{% static 'img/adventure_icon_3.svg' %}" alt="" width="75" height="75">
                    <h3><span> Everything </span>organized</h3>
                    <p>No need to worry about finding a place to stay or where to eat, just focus on creating
                        unforgettable memories. Book your tour today and experience the ultimate travel experience.".
                    </p>
                </div>
            </div>

            <div class="banner_2">
                <div class="wrapper d-flex align-items-center opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.3)"
                    style="background-color: rgba(0, 0, 0, 0.3);">
                    <div>
                        <h3>Your Perfect<br>Tour Experience</h3>
                        <p>Activities and accommodations</p>
                        <a href="{% url 'root:tours' %}" class="btn_1">Book Now </a>
                    </div>
                </div>
                <!-- /wrapper -->
            </div>
            <!-- /banner_2 -->

        </div>
        <!-- End container -->
    </div>
    <!-- End white_bg -->
</main>

templates/root/section_special_offer.html
{% load static %}
<main>
<div class="white_bg">
    <div class="container margin_60">
        <div class="row small-gutters categories_grid">
            <div class="col-sm-12 col-md-6">
                <a href="{% url 'root:offer_tours' %}">
                    <img src="{% static 'img/img_cat_home_1.jpg' %}" alt="" class="img-fluid">
                    <div class="wrapper">
                        <h2>Special Offers</h2>
                        <p> Pacific</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="row small-gutters mt-md-0 mt-sm-2">
                    <div class="col-sm-6">
                        <a href="{% url 'root:tours' %}">
                            <img src="{% static 'img/img_cat_home_2.jpg' %}" alt="" class="img-fluid">
                            <div class="wrapper">
                                <h2>Special Tours</h2>
                                <p> Pacific</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'root:daily_tours' %}">
                            <img src="{% static 'img/img_cat_home_3.jpg' %}" alt="" class="img-fluid">
                            <div class="wrapper">
                                <h2>Daily Tours</h2>
                                <p> Pacific</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm-12 mt-sm-2">
                        <a href="{% url 'root:userside_report' %}">
                            <img src="{% static 'img/img_cat_home_4.jpg' %}" alt="" class="img-fluid">
                            <div class="wrapper">
                                <h2>Reports About Us</h2>
                                <p> Pacific</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!--/categories_grid-->
    </div>
    <!-- /container -->
</div>
<!-- /white_bg -->
</main>

templates/root/userside_report.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}
<section class="parallax-window" data-parallax="scroll" data-image-src="{% static 'img/tour_box_9.jpg' %}"
    data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1 opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
        <div class="animated fadeInDown">
            <h1>Pacific tours</h1>
            <p>Feel the thrill of Pacific Tours.</p>
        </div>
    </div>
</section>

<main>
    <div class="container margin_60">
        <div class="row">
            <center>
            <a href="{% url 'manager:top_tours_report' %}">
            <div class="col-md-3" style="background-color: rgb(210, 127, 127);height: 70px;">
                <center style="margin-top: 23px;">
                    <h3 style="color: white;padding-top: 20px;"> Top  tours</h3>
                </center>
            </div>
            </a>
            <a href="{% url 'manager:top_5destinations' %}">
            <div class="col-md-3" style="background-color: rgb(210, 127, 127);height: 70px;">
                <center style="margin-top: 23px;">
                    <h3 style="color: white;padding-top: 20px;"> Top  Destination Report</h3>
                </center>
            </div>
            </a>
        </center>
        </div>
    </div>
</main>
{% endblock body %}