auth_system/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #import this

app_name = 'auth_system'


urlpatterns = [
    path('login_user/',views.login_user,name='login_user'),
    path('register_user/',views.register_user,name='register_user'),
    path('logout_user/',views.logout_user,name='logout_user'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_system/password_reset_done.html'), name='password_reset_done'),#second
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="auth_system/password_reset_confirm.html",success_url="/auth_system/login_user/"), name='password_reset_confirm'),#third
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth_system/password_reset_complete.html'), name='password_reset_complete'), #four

    path("password_reset", views.password_reset_request, name="password_reset")#first
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'


urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('<int:id>/del_contact_us/',views.del_contact_us, name="del_contact_us"),
    path('all_users',views.all_users,name='all_users'),
    path('bus_registration/',views.bus_registration,name='bus_registration'),
    path('add_bus_seat/',views.add_bus_seat,name='add_bus_seat'),
    path('<int:id>/del_bus/',views.del_bus, name="del_bus"),
    path('add_routes/',views.add_routes,name='add_routes'),
    path('add_address/',views.add_address,name='add_address'),
    path('add_schedules/',views.add_schedules,name='add_schedules'),
    path('add_special_tours/',views.add_special_tours,name='add_special_tours'),
    path('<int:id>/del_stours/',views.del_stours, name="del_stours"),
    path('<int:id>/stours_details/',views.stours_details, name="stours_details"),
    path('all_bookings/',views.all_bookings,name='all_bookings'),
    path('<int:sid>/<str:d>/ubb_details/',views.ubb_details,name='ubb_details'),
    path('tour_bookings/',views.tour_bookings,name='tour_bookings'),
    path('<int:id>/tb_details/',views.tb_details,name='tb_details'),
    path('top_5users/',views.top_5users,name='top_5users'),
    path('top_5destinations/',views.top_5destinations,name='top_5destinations'),
    path('all_users_report/',views.all_users_report,name='all_users_report'),
    path('top_tours_report/',views.top_tours_report,name='top_tours_report')
]

pacific/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),   # redirect to home page
    path('auth_system/',include('auth_system.urls')),
    path('manager/',include('manager.urls')),
    path('booking/',include('booking.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

root/urls.py
from django.urls import path
from . import views

app_name = 'root'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('about_us/',views.about_us,name='about_us'),
    path('mydashboard/',views.mydashboard,name='mydashboard'),
    path("search_bus/", views.search_bus, name="search_bus"),
    path('tours/',views.tours,name='tours'),
    path('daily_tours/',views.daily_tours,name='daily_tours'),
    path('offer_tours/',views.offer_tours,name='offer_tours'),
    path('<int:id>/tour_details/',views.tour_details,name='tour_details'),
    path('<int:id>/booking_details/',views.booking_details,name='booking_details'),
    path('<int:id>/tour_booking_details/',views.tour_booking_details,name='tour_booking_details'),
    path('userside_report/',views.userside_report,name='userside_report')
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render,redirect
from root.models import Mailbox
from django.contrib.auth.decorators import login_required
from auth_system.models import CustomUser
from booking.forms import Bus_registrationForm,Add_RoutesForm,Add_addressForm,Add_schedulesForm,add_bus_seatForm,Add_Special_toursForm
from django.contrib import messages
from booking.models import Bus,Address,Routes,Schedules,Seat,Special_Tours,BusBookings,BusBookings_details,STourBooking,STourBooking_details
from django.db.models import Count
from datetime import datetime
from .utils import pdf
from django.db.models import Avg, Max, Min
from django.db.models import OuterRef, Subquery
# Create your views here.
@login_required(login_url='auth_system:login_user') 
def dashboard(request):
    bus_count = Bus.objects.all().count()
    route_count = Routes.objects.all().count()
    schedules_count = Schedules.objects.all().count()
    users_count = CustomUser.objects.all().count()
    contact_count = Mailbox.objects.all().count()
    st_count = Special_Tours.objects.all().count()
    context={
        'bus_count':bus_count,
        'route_count':route_count,
        'schedules_count':schedules_count,
        'users_count':users_count - 2,
        'contact_count':contact_count,
        'st_count':st_count
    }
    return render(request,'manager/index.html',context)


@login_required(login_url='auth_system:login_user')  
def contact_us(request):
    data = Mailbox.objects.all()
    context = {
        'data':data
    }
    return render(request,'manager/contactus.html',context)

@login_required(login_url='auth_system:login_user') 
def del_contact_us(request,id):
    contact = Mailbox.objects.get(id=id)
    contact.delete()
    return redirect('manager:contact_us')

@login_required(login_url='auth_system:login_user') 
def all_users(request):
    users = CustomUser.objects.filter(user_type = 'customer')
    cnt = CustomUser.objects.all().count() - 2 # 1 for admin and 1 for manager 
    context = {
        'data':users,
        'cnt':cnt
    }
    return render(request,'manager/all_users.html',context)

@login_required(login_url='auth_system:login_user') 
def bus_registration(request):
    if request.method == 'POST':
        
        form = Bus_registrationForm(request.POST,request.FILES)   
        
        if form.is_valid():
            form.save()
            messages.success(request,'Bus added successfully.')
            return redirect('manager:bus_registration')
    else:
        form = Bus_registrationForm()

    context={
        'form':form,
        'cnt':Bus.objects.all().count(),
        'data':Bus.objects.all(),
        's_data':Seat.objects.all()
    } 
    return render(request,'manager/bus_registration.html',context)

@login_required(login_url='auth_system:login_user') 
def add_bus_seat(request):
    if request.method == 'POST':
        
        form = add_bus_seatForm(request.POST)   
        
        if form.is_valid():
            # print(request.POST['seat_name'])
            b = Bus.objects.get(pk=request.POST['bus_fk'])
            if Seat.objects.filter(bus_fk= request.POST['bus_fk']).exists():
                messages.success(request,f'Seats of Bus : {b} already exists.')
                return redirect('manager:add_bus_seat')

            else:
                if int(request.POST['seat_count']) > b.max_seats:
                    messages.success(request,f'Bus : {b} Seat count Out of Max seats count.')
                    return redirect('manager:add_bus_seat')
                    
                else:
                    seat_cnt = request.POST['seat_count']
                    for i in range(1,int(seat_cnt)+1):
                        s_name = request.POST['seat_name'] + str(i) # S+1 = S1
                        
                        b_fk = Bus.objects.get(pk=request.POST['bus_fk'])
                        Seat.objects.create(seat_name=s_name,bus_fk=b_fk)

            
            messages.success(request,'All Seats added successfully.')
            return redirect('manager:add_bus_seat')
    else:
        form = add_bus_seatForm()

    context = {
        'form':form,
    }
    return render(request,'manager/add_bus_seat.html',context)

@login_required(login_url='auth_system:login_user') 
def del_bus(request,id):
    bus_obj = Bus.objects.get(id=id)
    bus_obj.delete()
    return redirect('manager:bus_registration')

@login_required(login_url='auth_system:login_user') 
def add_routes(request):
    if request.method == 'POST':
        
        form = Add_RoutesForm(request.POST,request.FILES)   
        
        if form.is_valid():
            # print(request.POST['origin_fk'])
            if request.POST['origin_fk'] == request.POST['destination_fk']:
                messages.success(request,'Please do not select same city as origin and distanation.')
                return redirect('manager:add_routes')
            else:
                form.save()
                messages.success(request,'Route added successfully.')
                return redirect('manager:add_routes')
    else:
        form = Add_RoutesForm()
    context={
        'form':form,
        'cnt':Routes.objects.all().count(),
        'data':Routes.objects.all()
    } 
    return render(request,'manager/add_routes.html',context)

@login_required(login_url='auth_system:login_user') 
def add_address(request):
    if request.method == 'POST':
        
        form = Add_addressForm(request.POST,request.FILES)   
        
        if form.is_valid():
            # print(request.POST['origin_fk'])
            form.save()
            messages.success(request,'Address added successfully.')
            return redirect('manager:add_address')
    else:
        form = Add_addressForm()

    context={
        'form':form,
        'cnt':Address.objects.all().count(),
        'data':Address.objects.all()
    } 
    return render(request,'manager/add_address.html',context)

@login_required(login_url='auth_system:login_user') 
def add_schedules(request):
    if request.method == 'POST':
        
        form = Add_schedulesForm(request.POST,request.FILES)   
        
        if form.is_valid():
            # print(request.POST['origin_fk'])
            form.save()
            messages.success(request,'Schedule added successfully.')
            return redirect('manager:add_schedules')
    else:
        form = Add_schedulesForm()
    # d = Schedules.objects.get(id=1)
    # days = d.daysOfWeek
    # j = days.split(',')
    # for i in j:
    #     print(i.replace(' ',''))
    context={
        'form':form,
        'cnt':Schedules.objects.all().count(),
        'data':Schedules.objects.all()
    } 
    return render(request,'manager/add_shedules.html',context)


@login_required(login_url='auth_system:login_user') 
def add_special_tours(request):
    if request.method == 'POST':
        
        form = Add_Special_toursForm(request.POST,request.FILES)   
        
        if form.is_valid():
            print("hello")
            form.save()
            messages.success(request,'Tour added successfully.')
            return redirect('manager:add_special_tours')
    else:
        form = Add_Special_toursForm()

    context={
        'form':form,
        'cnt':Special_Tours.objects.all().count(),
        'data':Special_Tours.objects.all(), 
    }
    return render(request,'manager/add_special_tours.html',context)

@login_required(login_url='auth_system:login_user') 
def del_stours(request,id):
    bus_obj = Special_Tours.objects.get(id=id)
    bus_obj.delete()

    return redirect('manager:add_special_tours')

@login_required(login_url='auth_system:login_user') 
def stours_details(request,id):
    sd_obj = Special_Tours.objects.get(id=id)
    

    context={
        'data':sd_obj
    }
    
    return render(request,'manager/stours_details.html',context)


@login_required(login_url='auth_system:login_user') 
def all_bookings(request):
    current_date = datetime.now()
    #MyModel.objects.values('schedule_fk', 'travel_date').annotate(total=Count('id')).filter(total=1)
    #t = BusBookings.objects.filter(id__in=BusBookings.objects.values('schedules_fk', 'travel_date').annotate(min_id=Min('id')).values('min_id'))
    
    t = BusBookings.objects.filter(id=Subquery(
        BusBookings.objects.filter(
            schedules_fk=OuterRef('schedules_fk'),
            travel_date=OuterRef('travel_date'),travel_date__gte=current_date
        ).order_by('id').values('id')[:1]
    )).order_by('travel_date')


    #,id__in=distinct_data.keys()
    #! main
    #! data = BusBookings.objects.filter(travel_date__gte=current_date).values('id','schedules_fk','schedules_fk__route_fk__bus_fk__plate_no','total_price','schedules_fk__route_fk__origin_fk__city','schedules_fk__route_fk__destination_fk__city','travel_date').annotate(bcnt=Count('schedules_fk')).order_by('travel_date')
    #! main end
    
    # total_seat_cnt = BusBookings_details.objects.filter(busbookings_fk__in=list1).values('busbookings_fk','busbookings_fk__schedules_fk__route_fk__bus_fk__max_seats').annotate(cnt=Count('busbookings_fk')).order_by()
    
    
    # print()
    # print(total_seat_cnt)
    # print(data)
    # print()
    context={
        'data':t,
        # 'data_seat':total_seat_cnt
    }
    
    return render(request,'manager/all_bookings.html',context)

@login_required(login_url='auth_system:login_user') 
def ubb_details(request,sid,d):
    #b_data = BusBookings.objects.get(id=id)
    b_data = BusBookings.objects.filter(schedules_fk=sid)[:1]
    obj = BusBookings_details.objects.filter(busbookings_fk__paid=True,busbookings_fk__schedules_fk=sid,busbookings_fk__travel_date=d)

    tmp_dict = {}
    for i in b_data:

templates/manager/add_bus_seat.html
{% extends 'manager/layout.html' %}
{% load static %}


{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Bus Seat Registration Page</h4>
                    <span></span>
                </div>
            </div>

        </div>
        {% for message in messages %}

        <div class="alert alert-danger">
            {{ message }}
        </div>

        {% endfor %}

        <!-- row -->
        <div class="card-body">
            <div class="form-validation">
                <div class="alert alert-primary alert-dismissible fade show">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close"><span><i
                                class="mdi mdi-btn-close"></i></span>
                    </button>
                    <div class="media">
                        <div class="media-body">
                            <h5 class="mt-1 mb-1">Please Read</h5>
                            <p class="mb-0">1.  for <b>' Seat Name'</b> Your need to enter just one word that will
                                preceding word like 'T' or 'S' where bus Name will be <b> T1, T2 </b> till total count
                                <br>
                                2.  It might take Some time to create all seats that your entered in <b> 'seat count' </b>
                            </p>
                        </div>
                    </div>
                </div>
                <hr><br>
                <form class="" action="." method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-12">

                            {% for i in form %}
                            <div class="mb-3 row">
                                <label class="col-lg-4 col-form-label">{{ i.label }}
                                    <span class="text-danger">*{{i.error}}</span>
                                </label>
                                <div class="col-lg-6">
                                    {{ i }}
                                </div>
                            </div>
                            {% endfor %}




                            <div class="mb-3 row">
                                <div class="col-lg-8 ms-auto">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        

    </div>
</div>
<!--**********************************
            Content body end
        ***********************************-->




{% endblock body %}

templates/manager/all_users_report.html
<!DOCTYPE html>
<html>
	<head>
		<style>
			table {
				border-collapse: collapse;
			}
			th {
				background-color:green;
				Color:white;
			}
			th, td {
				width:200px;
				text-align:center;
				border:1px solid black;
				padding:5px
			
			}
			.geeks {
				border-right:hidden;
			}
			.gfg {
				border-collapse:separate;
				border-spacing:0 15px;
			}
			h1 {
				color:green;
			}
			@page {
				size: Letter;
				margin: 0in 0.44in 0.2in 0.44in;
			}
		</style>
	</head>
	<body>
		<center>
		<h1>Pacific Tours and Travels</h1>
		<h2>{{ msg }}</h2>
		<h3>{{rest}}</h3>
		<h4>Total  : - {{cnt}}</h4>
		<h4>Date : - {{date}}</h4>
		<table>
			<tr>
				<th>Username</th>
				<th>Email</th>
				
				<th>Contact Number</th>
			</tr>
		</table>
		<table class = "gfg">
			{% for i in data %}
			<tr>
				<td class = "geeks">{{i.username}}</td>
				<td>{{i.email}}</td>
				
				<td>{{ i.contact }}</td>
			</tr>
			{% endfor %}
            
		</table>
		</center>
	</body>
</html>

templates/manager/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="description" content="Dashboard - Pacific Tours & Travels" />
    <meta property="og:title" content="Dashboard - Pacific Tours & Travels" />
    <meta property="og:description" content="Dashboard - Pacific Tours & Travels" />
    <meta property="og:image" content="https://davur.dexignzone.com/xhtml/page-error-404.html" />
    <meta name="format-detection" content="telephone=no">
    <title>Dashboard - Pacific Tours & Travels </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashboard/images/favicon.png' %}">
    <link href="{% static 'dashboard/vendor/jqvmap/css/jqvmap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dashboard/vendor/chartist/css/chartist.min.css' %}">
    <link href="{% static 'dashboard/vendor/bootstrap-select/dist/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/css/LineIcons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dashboard/icons/flaticon/flaticon.css' %}">
    <link href="{% static 'dashboard/vendor/datatables/css/jquery.dataTables.min.css' %} " rel="stylesheet">
    <!-- Datatable -->

    <!-- Custom Stylesheet -->
    <link href="{% static 'dashboard/vendor/bootstrap-select/dist/css/bootstrap-select.min.css' %}" rel="stylesheet">


</head>

<body>

    <!--*******************
        Preloader start
    ********************-->

    <!--*******************
        Preloader end
    ********************-->

    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="{% url 'manager:dashboard' %}" class="brand-logo">
                <img class="logo-abbr" src="{% static 'dashboard/images/logo.png' %}" alt="">
                <img class="logo-compact" src="{% static 'dashboard/images/logo-text.png' %}" alt="">
                <img class="brand-title" src="{% static 'dashboard/images/logo-text.png' %}" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>


        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">

                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown notification_dropdown">
                                <a class="nav-link dz-fullscreen primary" href="#">
                                    <svg id="Capa_1" enable-background="new 0 0 482.239 482.239" height="22"
                                        viewBox="0 0 482.239 482.239" width="22" xmlns="../../www.w3.org/2000/svg.html">
                                        <path
                                            d="m0 17.223v120.56h34.446v-103.337h103.337v-34.446h-120.56c-9.52 0-17.223 7.703-17.223 17.223z"
                                            fill="" />
                                        <path
                                            d="m465.016 0h-120.56v34.446h103.337v103.337h34.446v-120.56c0-9.52-7.703-17.223-17.223-17.223z"
                                            fill="" />
                                        <path
                                            d="m447.793 447.793h-103.337v34.446h120.56c9.52 0 17.223-7.703 17.223-17.223v-120.56h-34.446z"
                                            fill="" />
                                        <path
                                            d="m34.446 344.456h-34.446v120.56c0 9.52 7.703 17.223 17.223 17.223h120.56v-34.446h-103.337z"
                                            fill="" />
                                    </svg>
                                </a>
                            </li>


                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
                                    <div class="header-info">
                                        <span>Hello, <strong>{{user}}</strong></span>
                                    </div>
                                    <img src="{% static 'dashboard/images/profile/pic1.jpg' %}" width="20" alt="" />
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{% url 'auth_system:logout_user' %}" class="dropdown-item ai-icon">
                                        <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger"
                                            width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                            <polyline points="16 17 21 12 16 7"></polyline>
                                            <line x1="21" y1="12" x2="9" y2="12"></line>
                                        </svg>
                                        <span class="ms-2">Logout </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="deznav">
            <div class="deznav-scroll">
                <ul class="metismenu" id="menu">
                    <li><a class=" ai-icon" href="{% url 'manager:dashboard' %}" aria-expanded="false">
                            <i class="flaticon-381-networking"></i>
                            <span class="nav-text">Dashboard</span>
                        </a>

                    </li>
                    <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="flaticon-381-notepad"></i>
                            <span class="nav-text">Bookings</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:all_bookings' %}">Upcoming Bus Bookings</a></li>
                            <li><a href="{% url 'manager:tour_bookings' %}">Tour Bookings</a></li>
                        </ul>
                    </li>
                    <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="flaticon-381-television"></i>
                            <span class="nav-text">Bus</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:add_address' %}">Add address</a></li>
                            <li><a href="{% url 'manager:bus_registration' %}">Bus Registration</a></li>
                            <li><a href="{% url 'manager:add_bus_seat' %}">Bus Seat Registration</a></li>
                            <li><a href="{% url 'manager:add_routes' %}">Add Routes</a></li>
                            <li><a href="{% url 'manager:add_schedules' %}">Add Schedules</a></li>


                        </ul>
                    </li>
                    <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="flaticon-381-controls-3"></i>
                            <span class="nav-text">Special Tours</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:add_special_tours' %}">Add Special Tours</a></li>

                        </ul>
                    </li>

                    <li><a class=" ai-icon" href="{% url 'manager:contact_us' %}" aria-expanded="false">
                            <i class="flaticon-381-database"></i>
                            <span class="nav-text">Contacts</span>

                        </a>

                    </li>
                    <li><a class=" ai-icon" href="{% url 'manager:all_users' %}" aria-expanded="false">
                            <i class="la la-user"></i>
                            <span class="nav-text">User's</span>

                        </a>

                    </li>
                    
                </ul>

                <div class="add-menu-sidebar">
                    <img src="images/icon1.png" alt="" />
                    <p>Register address through button bellow</p>
                    <a href="{% url 'manager:add_address' %}" class="btn bg-white text-black">+ Add Address</a>
                </div>
                <div class="copyright">
                    <p><strong>Pacific Tours & Travels - Admin Dashboard</strong> © 2023 All Rights Reserved</p>
                    <p>Made with <span class="heart"></span> by Pacific Projects </p>
                </div>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->

        <!--**********************************
            Content body start
        ***********************************-->

        {% block body %}

        {% endblock body %}

        <!--**********************************
            Content body end
        ***********************************-->

        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by Pacific Tours & Travels </a> 2023</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

        <!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'dashboard/vendor/global/global.min.js' %} "></script>
    <script src="{% static 'dashboard/vendor/bootstrap-select/dist/js/bootstrap-select.min.js' %} "></script>
    <script src="{% static 'dashboard/vendor/chart.js/Chart.bundle.min.js' %} "></script>
    <script src="{% static 'dashboard/js/custom.min.js' %} "></script>
    <script src="{% static 'dashboard/js/deznav-init.js' %} "></script>

    <!-- Counter Up -->
    <script src="{% static 'dashboard/vendor/waypoints/jquery.waypoints.min.js' %} "></script>
    <script src="{% static 'dashboard/vendor/jquery.counterup/jquery.counterup.min.js' %} "></script>

    <!-- Apex Chart -->
    <script src="{% static 'dashboard/ vendor/apexchart/apexchart.js' %}"></script>

    <!-- Chart piety plugin files -->
    <script src="{% static 'dashboard/vendor/peity/jquery.peity.min.js' %} "></script>

    <!-- Dashboard 1 -->
    <script src="{% static 'dashboard/js/dashboard/dashboard-1.js' %} "></script>
    <script src="{% static 'dashboard/vendor/datatables/js/jquery.dataTables.min.js' %} "></script>

    <!-- Datatable -->
    <!-- <script src="{% static 'dashboard/vendor/datatables/js/jquery.dataTables.min.js' %}"></script> -->
    <script src="{% static 'dashboard/js/plugins-init/datatables.init.js' %}"></script>



</body>


</html>