auth_system/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #import this

app_name = 'auth_system'


urlpatterns = [
    path('login_user/',views.login_user,name='login_user'),
    path('register_user/',views.register_user,name='register_user'),
    path('logout_user/',views.logout_user,name='logout_user'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_system/password_reset_done.html'), name='password_reset_done'),#second
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="auth_system/password_reset_confirm.html",success_url="/auth_system/login_user/"), name='password_reset_confirm'),#third
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth_system/password_reset_complete.html'), name='password_reset_complete'), #four

    path("password_reset", views.password_reset_request, name="password_reset")#first
]

pacific/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),   # redirect to home page
    path('auth_system/',include('auth_system.urls')),
    path('manager/',include('manager.urls')),
    path('booking/',include('booking.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

root/urls.py
from django.urls import path
from . import views

app_name = 'root'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('about_us/',views.about_us,name='about_us'),
    path('mydashboard/',views.mydashboard,name='mydashboard'),
    path("search_bus/", views.search_bus, name="search_bus"),
    path('tours/',views.tours,name='tours'),
    path('daily_tours/',views.daily_tours,name='daily_tours'),
    path('offer_tours/',views.offer_tours,name='offer_tours'),
    path('<int:id>/tour_details/',views.tour_details,name='tour_details'),
    path('<int:id>/booking_details/',views.booking_details,name='booking_details'),
    path('<int:id>/tour_booking_details/',views.tour_booking_details,name='tour_booking_details'),
    path('userside_report/',views.userside_report,name='userside_report')
]

auth_system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
user_choice = (
    ('manager','Manager'),
    ('customer','Customer')    # first used in database link and second Display name    
)
gender_choice =(
    ('male','Male'),
    ('female','Famale'),
    ('not referred to say','Not referred to say')
)

class CustomUser(AbstractUser):
    
    user_type = models.CharField(max_length=10,choices=user_choice,default='customer')
    contact = models.CharField(max_length=10,default='')
    gender = models.CharField(max_length=50,choices=gender_choice,default='male')

auth_system/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class registerUser(UserCreationForm):

    class Meta:
        model = CustomUser  #database 
        fields = ('username','first_name','last_name','email','password1', 'password2','contact','gender')
        widgets = {
                'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username'}),
                'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name'}),
                'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Last Name'}),
                'email':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your Email'}),
                'contact':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your Contact'}),
                'password1':forms.TextInput(attrs={'class':'form-control','type':'password','style':'width:350px'}),
                'password2':forms.TextInput(attrs={'class':'form-control'}),
                # 'gender':forms.CheckboxInput(attrs={'class':"form-group",'type':'checkbox','style':'height:10px'}),
                'gender':forms.RadioSelect(attrs={'class':"form-check-flex list-unstyled ",'type':'radio','style':'height:20px'})
        }
    
class loginUser(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'Password'}))
        

auth_system/views.py
from django.shortcuts import render,redirect
from .forms import registerUser,loginUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login , logout
from django.contrib import messages
from django.utils.safestring import mark_safe
from .models import CustomUser
from django.conf import settings
#
from django.utils.safestring import mark_safe
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm

from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes


# Create your views here.
def login_user(request):
    #here it is form for login user
    form = loginUser()
    err = 0
    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']
    
        user = authenticate(request,username=username,password = password)
        
        if user is not None:
            login(request, user) # login with username and password
            #it will check role for user
            if request.user.user_type == 'customer':
                return redirect('root:index')
            elif request.user.user_type == 'manager':
                return redirect('manager:dashboard') 
            
        else:
            messages.error(request,'Username or Password not correct')
            return render(request,'Auth_system/login.html',{'form':form})
    context = {
            'form':form
    }
    return render(request,'auth_system/login.html',context)

def register_user(request):
    form = registerUser()
    if request.method == 'POST':
        form = registerUser(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('auth_system:login_user') #loginpage
            
        else:
            # messages.info(request,mark_safe('1. Email must be in format like tmp@gmail.com <br/>2. Password Contains at list 8 character, alphabets and specials'))
            return render(request,'Auth_system/register.html',{'form':form})
    
    context = {
        'form':form
    }
    return render(request,'auth_system/register.html',context)


@login_required(login_url='auth_system:login_user') 
def logout_user(request):
    logout(request)

    return redirect('auth_system:login_user')


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = CustomUser.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "auth_system/password_reset.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
                        
						send_mail(subject, email, settings.EMAIL_HOST_USER , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
                    
					return redirect("auth_system:password_reset_done")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="auth_system/password_reset.html", context={"password_reset_form":password_reset_form})

templates/auth_system/login.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}
<main>
    <section id="hero" class="login">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-4 col-lg-5 col-md-6 col-sm-8">
                    <div id="login">
                        <div class="text-center"><img src="{% static 'img/logo_sticky.png' %}" alt="Image" width="160"
                                height="34"></div>
                        <hr>
                        <h3 align="center"><b> Login </b></h3>
                        <form accept="{% url 'auth_system:login_user' %}" method="POST">
                            {% csrf_token %}
                            {% for message in messages %}

                            <div class="alert alert-danger">
                                {{ message }}
                            </div>

                            {% endfor %}
                            
                            {{form}}
                            <p class="small">
                                <a href="{% url 'auth_system:password_reset' %}">Forgot Password?</a>
                            </p>
                            <input type="submit" class="btn_full_outline btn_full" value="Login">
                            <p class="small">
                                <a href="{% url 'auth_system:register_user' %}">
                                    <center>Register?</center>
                                </a>
                            </p>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End main -->
{% endblock body %}

templates/auth_system/password_reset.html
{% extends 'root/layout.html' %}
{% load static %}
   
{% block body %}
<div style='margin-top:100px;margin-bottom: 2400px;'>
    <!--Reset Password-->
	<div class="container p-5">
        <h2 class="font-weight-bold mt-3">Reset Password</h2>
        <hr>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form action="{% url 'auth_system:password_reset' %}" method="POST">
            {% csrf_token %}
            {{ password_reset_form }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
    </div> 
</div>
{% endblock body %}

templates/auth_system/password_reset_complete.html
{% extends "root/layout.html" %}

{% block content %} 
  
  <!--Password Reset Complete-->
    <div class="container p-4" style='margin-top:200px;'>
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'auth_system:login_user' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/auth_system/password_reset_confirm.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}

    <!--Reset Password-->
	<div class="container p-5" style="margin-top:100px;">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock body %}

templates/auth_system/password_reset_done.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}

    <!--Reset Password-->
	<div class="container p-5" style='margin-top:100px;margin-bottom:400px;'>
        <h2 class="font-weight-bold mt-3">Password reset sent</h2>
          <hr>
          <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
    </div>

{% endblock body %}

templates/auth_system/register.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}
<main>
    <section id="hero" class="login">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-4 col-lg-5 col-md-6 col-sm-8">
                    <div id="login">
                        <div class="text-center"><img src="{% static 'img/logo_sticky.png' %}" alt="Image" width="160"
                                height="34"></div>
                        <hr>
                        <h3 align="center"><b> Register </b></h3>
                        <form action="{% url 'auth_system:register_user' %}" method="POST">
                            {% csrf_token %}


                            <div class="form-group">
                                <label>Username</label>
                                {{form.username}}
                                <small class="text-danger">{{form.username.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label>First Name</label>
                                {{form.first_name}}
                                <small class="text-danger">{{form.first_name.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                {{form.last_name}}
                                <small class="text-danger">{{form.last_name.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                {{form.email}}
                                <small class="text-danger">{{form.email.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label>Contact Number</label>
                                {{form.contact}}

                            </div>

                            <div class="form-group">
                                <label>Gender</label>
                                {{form.gender}}
                            </div>
                            <div class="form-group">
                                <label>Password?</label><br>
                                {{form.password1}}
                                <small class="text-danger">{{form.password1.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label>Re-enter Password</label><br>
                                {{form.password2}} <br>
                                <small class="text-danger">{{form.password2.errors|striptags}}</small>
                            </div>

                            <p class="small">
                                <a href="#">Forgot Password?</a>
                            </p>

                            <input type="submit" class="btn_full_outline btn_full" value="Create an account">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End main -->
{% endblock body %}