booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('<int:sid>/<str:date>/book_seat/',views.book_seat,name='book_seat'),
    path('success/',views.success,name='success'),
    path('success_stours/',views.success_stours,name='success_stours'),
    path('<int:id>/pdf_busbooking/',views.pdf_busbooking,name='pdf_busbooking'),
    path('<int:id>/pdf_tourbooking/',views.pdf_tourbooking,name='pdf_tourbooking')
]

pacific/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),   # redirect to home page
    path('auth_system/',include('auth_system.urls')),
    path('manager/',include('manager.urls')),
    path('booking/',include('booking.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

root/urls.py
from django.urls import path
from . import views

app_name = 'root'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('about_us/',views.about_us,name='about_us'),
    path('mydashboard/',views.mydashboard,name='mydashboard'),
    path("search_bus/", views.search_bus, name="search_bus"),
    path('tours/',views.tours,name='tours'),
    path('daily_tours/',views.daily_tours,name='daily_tours'),
    path('offer_tours/',views.offer_tours,name='offer_tours'),
    path('<int:id>/tour_details/',views.tour_details,name='tour_details'),
    path('<int:id>/booking_details/',views.booking_details,name='booking_details'),
    path('<int:id>/tour_booking_details/',views.tour_booking_details,name='tour_booking_details'),
    path('userside_report/',views.userside_report,name='userside_report')
]

booking/forms.py
from django import forms
from datetime import datetime
from .models import Bus,Routes,Address,Schedules,Special_Tours

class Bus_registrationForm(forms.ModelForm):
        class Meta:
                model = Bus
                fields = ['name','driver_name','contact','plate_no','seat_type','max_seats']
                widgets={
                        'name':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Fullname'}),
                        'driver_name':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Driver name'}),
                        'contact':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Contact Number'}),
                        'plate_no':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Plate no'}),
                        'seat_type':forms.Select(attrs={'class':'form-select','type':'input','placeholder':'Enter Plate no'}),
                        
                        'max_seats':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Maximum Seats'}) 
                }

class Add_RoutesForm(forms.ModelForm):
        class Meta:
                model = Routes
                fields = ['bus_fk','origin_fk','destination_fk','stops_city','distance','boarding_point','dropping_point']
                widgets={
                        'bus_fk':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'origin_fk':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'destination_fk':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'stops_city':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter all stops'}),
                        'distance':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Distance'}),
                        'boarding_point':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Boarding Point'}),
                        'dropping_point':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Dropping Point'})

                }

class Add_addressForm(forms.ModelForm):
        class Meta:
                model = Address
                fields = ['city','state','pincode']
                widgets = {
                        'city':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter City name'}),
                        'state':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter State name'}),
                        'pincode':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Pincode'}),
                }

class Add_schedulesForm(forms.ModelForm):
        class Meta:
                model = Schedules
                fields = ['route_fk','departureTime','arrivalTime','daysOfWeek','duration','price']
                widgets = {
                        'route_fk':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'departureTime' : forms.NumberInput(attrs={'class': 'form-control datepicker-default form-control picker__input','type':'time'}),
                        'arrivalTime' : forms.NumberInput(attrs={'class': 'form-control datepicker-default form-control picker__input','type':'time'}),
                        'daysOfWeek' : forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter like "sunday, monday, tuesday,"'}),
                        'duration':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Duration'}),
                        'price':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Price for ticket'})
                }

class add_bus_seatForm(forms.Form):
        seat_name = forms.CharField(max_length=100,required=True)
        seat_count = forms.IntegerField(required=True)
        bus_fk = forms.ModelChoiceField(Bus.objects,required=True)

        def __init__(self, *args, **kwargs):
                super(add_bus_seatForm, self).__init__(*args, **kwargs)
                for visible in self.visible_fields():
                        visible.field.widget.attrs['class'] = 'form-control input-height'
                        visible.field.widget.attrs['placeholder'] = 'please Enter Details'

class Add_Special_toursForm(forms.ModelForm):
        class Meta:
                model = Special_Tours
                fields = ['name','boarding_point','dropping_point','offer_per','offer','start_date','end_date','time','bus_fk_k','description','schedule','origin_fk_k','destination_fk_k','price','total_days','img1','img2','img3','img4']
                widgets={
                        'name':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Fullname'}),
                        'offer_per':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Offer per'}),
                        
                        'start_date': forms.NumberInput(attrs={'class': 'form-control datepicker-default form-control picker__input','type':'date'}),
                        'end_date' : forms.NumberInput(attrs={'class': 'form-control datepicker-default form-control picker__input','type':'date'}),
                        'time' : forms.NumberInput(attrs={'class': 'form-control datepicker-default form-control picker__input','type':'time'}),
                        'bus_fk_k':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'description' : forms.Textarea(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Descripion'}),
                        'schedule' : forms.Textarea(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Schedule'}),
                        'origin_fk_k':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'destination_fk_k':forms.Select(attrs={'class':'form-select','type':'input'}),
                        'price':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Price for tour'}),
                        'total_days':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter total days'}),
                        'boarding_point':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Boarding Point'}),
                        'dropping_point':forms.TextInput(attrs={'class':'form-control input-height','type':'input','placeholder':'Enter Dropping Point'})
                }




booking/views.py
from django.shortcuts import render,redirect
from .models import Schedules,Bus,Seat,BusBookings,BusBookings_details,STourBooking,STourBooking_details,Special_Tours
from auth_system.models import CustomUser
from django.utils import timezone
import razorpay
from django.views.decorators.csrf import csrf_exempt
from datetime import timedelta,datetime,time
#email
from django.conf import settings
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.core.mail import EmailMessage
from django.template.loader import get_template,render_to_string
from django.contrib.auth.decorators import login_required
import socket
from .utils import send_email,send_email_manager
#pdf 
from weasyprint import HTML
import os
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse


# Create your views here.
@login_required(login_url='auth_system:login_user') 
def book_seat(request,sid,date):

    

    s_obj = Schedules.objects.get(id=sid)
    bus_s_obj = Bus.objects.get(id=s_obj.route_fk.bus_fk.id)

    date_only = date
    seat_booked = BusBookings_details.objects.filter(busbookings_fk__schedules_fk=s_obj,date=date_only,busbookings_fk__paid=True)#,date=date_only.strftime('%Y/%m/%d')
    s_list = [i.seat_fk.seat_name for i in seat_booked]
    seats = Seat.objects.exclude(seat_name__in=s_list)
    available_seats = Seat.objects.filter(bus_fk=bus_s_obj,id__in=seats)# i added here bus_fk=bus_s_obj,

    user_id = CustomUser.objects.get(id=request.user.id)

    if request.method == 'POST':

        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        
        seats_list = request.POST.getlist('seats')
        

        t_price = len(seats_list) * int(s_obj.price)
        
        fname = first_name+' '+last_name

        BusBookings.objects.create(name=fname,total_price=str(t_price),user_fk=user_id,schedules_fk=s_obj,travel_date=date)
        busb_fk = BusBookings.objects.latest('id')

        for i in seats_list:
            seat = Seat.objects.get(seat_name=i)

            BusBookings_details.objects.create(busbookings_fk=busb_fk,seat_fk=seat,date=date)

        #for razorpay
        t_price= t_price*100
        client = razorpay.Client(auth=("rzp_test_susforIvG6nYky", "VUQ8dfvBSkVS9Lstz9r1pQ9r"))
        payment = client.order.create({'amount': t_price, 'currency': 'INR','payment_capture': '1'})

        busb_fk.razorpay_order_id = payment['id']
        busb_fk.save()
        return render(request, 'booking/razorpay.html', {'payment': payment})
    
    context ={
        'data':s_obj,
        'date':date,
        'seats':available_seats,
        's_count':available_seats.count()
        
    }
    return render(request,'root/book_seat.html',context)


@csrf_exempt
def success(request):
    flag = ''
    try:
        # connect to the host -- tells us if the host is actually
        # reachable
        socket.create_connection(("1.1.1.1", 53))
        flag='net_on'
    except OSError:
        flag='net_off'

    if request.method == "POST":
        a = request.POST
        order_id = ""
        for key , val in a.items():
            if key == "razorpay_order_id":
                order_id = val
                break
    
        book = BusBookings.objects.filter(razorpay_order_id = order_id).first()
        book.paid = True
        book.save()

        l_user = CustomUser.objects.get(pk=request.user.id)
        subject1 = "Your Seat Is Booked  - Pacific"
        msg = f'Your Seat has been Booked and Razorpay payment id is : {order_id}'
        to_mail1 = l_user.email
        tmp = 'booking/email_seatBook_successful.html'
        
        #this mail will go to user 
        #from utils.py user defined function 
        send_email(subject=subject1,to_mail=to_mail1,message=msg,tmp_url=tmp)

        #this mail will go to manager 
        subject1 = "Seat Booked - Pacific"
        msg = f'Seat Booked by {book.name} from: {book.schedules_fk}'
        to_mail1 = 'settings.EMAIL_HOST_USER'
        tmp = 'booking/email_seatBook_manager.html'
        n=book.name
        send_email_manager(subject=subject1,message=msg,tmp_url=tmp,name=n)

        #admin side email send kravo

    return render(request, "booking/success.html")

@csrf_exempt
def success_stours(request):
    flag = ''
    try:
        # connect to the host -- tells us if the host is actually
        # reachable
        socket.create_connection(("1.1.1.1", 53))
        flag='net_on'
    except OSError:
        flag='net_off'

    if request.method == "POST":
        a = request.POST
        order_id = ""
        for key , val in a.items():
            if key == "razorpay_order_id":
                order_id = val
                break
    
        book = STourBooking.objects.filter(razorpay_order_id = order_id).first()
        book.paid = True
        book.save()

        l_user = CustomUser.objects.get(pk=request.user.id)
        subject1 = "Your Seat Is Booked For Tour- Pacific"
        msg = f'Your Seat has been Booked for Tour: {book.special_tours_fk.name} and Razorpay payment id is : {order_id}'
        to_mail1 = l_user.email
        tmp = 'booking/email_seatBook_successful.html'
        
        #this mail will go to user 
        #from utils.py user defined function created for own purpose
        send_email(subject=subject1,to_mail=to_mail1,message=msg,tmp_url=tmp)

        #this mail will go to manager 
        subject1 = "Seat Booked For Tour- Pacific"
        msg = f'Seat Booked by {book.name} for: {book.special_tours_fk.name}'
        to_mail1 = 'settings.EMAIL_HOST_USER'
        tmp = 'booking/email_seatBook_manager.html'
        n=book.name
        send_email_manager(subject=subject1,message=msg,tmp_url=tmp,name=n)

        #admin side email send kravo

    return render(request, "booking/success.html")

download_path = os.path.join(settings.MEDIA_ROOT,'invoice.pdf')
def pdf_busbooking(request,id):

    data_booking = BusBookings.objects.get(id=id)
    seats = BusBookings_details.objects.filter(busbookings_fk=data_booking)

    context = {
        'data':data_booking,
        'seats':seats,
        's_cnt':seats.count()
    }    

    template_render  = render_to_string('booking/invoice.html', context)
    html = HTML(string=template_render)
    html.write_pdf(target=download_path)

    fs = FileSystemStorage(settings.MEDIA_ROOT)
    with fs.open('invoice.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="invoice.pdf"'
        return response
    return response

download_path = os.path.join(settings.MEDIA_ROOT,'invoice.pdf')
def pdf_tourbooking(request,id):
    dis = ''
    data_booking = STourBooking.objects.get(id=id)
    tour = Special_Tours.objects.get(id=data_booking.special_tours_fk.id)
    seats = STourBooking_details.objects.filter(stourbooking_fk=data_booking)
    if tour.offer:
        dis = tour.price * 10 / 100
    context = {
        'data':data_booking,
        'seats':seats,
        's_cnt':seats.count(),
        'dis':dis
    }    

    template_render  = render_to_string('booking/invoice_tours.html', context)
    html = HTML(string=template_render)
    html.write_pdf(target=download_path)

    fs = FileSystemStorage(settings.MEDIA_ROOT)
    with fs.open('invoice.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="invoice.pdf"'
        return response
    return response

templates/booking/invoice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        #invoice {
            padding: 30px;
        }

        .invoice {
            position: relative;
            background-color: #FFF;
            min-height: 680px;
            padding: 15px
        }

        .invoice header {
            padding: 10px 0;
            margin-bottom: 20px;
            border-bottom: 1px solid #3989c6
        }

        .invoice .company-details {
            text-align: right
        }

        .invoice .company-details .name {
            margin-top: 0;
            margin-bottom: 0
        }

        .invoice .contacts {
            margin-bottom: 20px
        }

        .invoice .invoice-to {
            text-align: left
        }

        .invoice .invoice-to .to {
            margin-top: 0;
            margin-bottom: 0
        }

        .invoice .invoice-details {
            text-align: right
        }

        .invoice .invoice-details .invoice-id {
            margin-top: 0;
            color: #3989c6
        }

        .invoice main {
            padding-bottom: 50px
        }

        .invoice main .thanks {
            margin-top: -100px;
            font-size: 2em;
            margin-bottom: 50px
        }

        .invoice main .notices {
            padding-left: 6px;
            border-left: 6px solid #3989c6
        }

        .invoice main .notices .notice {
            font-size: 1.2em
        }

        .invoice table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 20px
        }

        .invoice table td,
        .invoice table th {
            padding: 15px;
            background: #eee;
            border-bottom: 1px solid #fff
        }

        .invoice table th {
            white-space: nowrap;
            font-weight: 400;
            font-size: 16px
        }

        .invoice table td h3 {
            margin: 0;
            font-weight: 400;
            color: #3989c6;
            font-size: 1.2em
        }

        .invoice table .qty,
        .invoice table .total,
        .invoice table .unit {
            text-align: right;
            font-size: 1.2em
        }

        .invoice table .no {
            color: #fff;
            font-size: 1.6em;
            background: #3989c6
        }

        .invoice table .unit {
            background: #ddd
        }

        .invoice table .total {
            background: #3989c6;
            color: #fff
        }

        .invoice table tbody tr:last-child td {
            border: none
        }

        .invoice table tfoot td {
            background: 0 0;
            border-bottom: none;
            white-space: nowrap;
            text-align: right;
            padding: 10px 20px;
            font-size: 1.2em;
            border-top: 1px solid #aaa
        }

        .invoice table tfoot tr:first-child td {
            border-top: none
        }

        .invoice table tfoot tr:last-child td {
            color: #3989c6;
            font-size: 1.4em;
            border-top: 1px solid #3989c6
        }

        .invoice table tfoot tr td:first-child {
            border: none
        }

        .invoice footer {
            width: 100%;
            text-align: center;
            color: #777;
            border-top: 1px solid #aaa;
            padding: 8px 0
        }

        @page {
            size: Letter;
            margin: 0in 0.44in 0.2in 0.44in;
        }

        @media print {
            .invoice {
                font-size: 11px !important;
                overflow: hidden !important
            }

            @page {
                size: Letter;
                margin: 0in 0.44in 0.2in 0.44in;
            }

            .invoice footer {
                position: absolute;
                bottom: 10px;
                page-break-after: always
            }

            .invoice>div:last-child {
                page-break-before: always
            }
        }
    </style>
</head>

<body>
    <div id="invoice">


        <div class="invoice overflow-auto">
            <div style="min-width: 600px">
                <header>
                    <div class="row">
                        <div class="col">
                            <a target="_blank" href="https://lobianijs.com">
                                <img src="http://lobianijs.com/lobiadmin/version/1.0/ajax/img/logo/lobiadmin-logo-text-64.png"
                                    data-holder-rendered="true" />
                            </a>
                        </div>
                        <div class="col company-details">
                            {% comment %} <h2 class="name">
                                <a target="_blank" href="https://lobianijs.com">
                                    {{mylist}}
                                </a>
                            </h2> {% endcomment %}
                            <div>Pacific Tours & Travels</div>
                            <div>+(91) 96623 24734</div>
                            <div>pacifictourtravels23@gmail.com</div>
                        </div>
                    </div>
                </header>
                <main>
                    <div class="row contacts">
                        <div class="col invoice-to">
                            <div class="text-gray-light">INVOICE TO:</div>
                            <h2 class="to">{{ data.user_fk }}</h2>

                            <div class="email"><a href="">{{ data.user_fk.email }}</a></div><br>
							<div class="email">Booked By: {{data.name}}</div>
                        </div>
                        <div class="col invoice-details">
                            <h1 class="invoice-id">INVOICE</h1>
                            <h2 class="to">{{ data.schedules_fk.route_fk.bus_fk.name }} - {{ data.schedules_fk.route_fk.bus_fk.seat_type }}</h2>
                            <div class="date">Travel Date: {{data.travel_date}} </div>
                            <div class="date">Departure Time: {{data.schedules_fk.departureTime}} </div>
                            
                            <div class="date">Arrival Time: {{data.schedules_fk.arrivalTime}} </div>
							<div class="date">Booking Id: {{data.id}} </div>
                        </div>
                    </div>
                    <table border="0" cellspacing="0" cellpadding="0">
                        <thead>
                            <tr>
                                {% comment %} <th>#</th> {% endcomment %}
                                <th class="text-left">Travel From/To</th>
                                <th class="text-right">Total Seat</th>
                                <th class="text-right">Unit Price</th>
                                <th class="text-right">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <tr>
                                {% comment %} <td class="no">04</td> {% endcomment %}
                                <td class="text-left">
                                    <h3>
                                        {{data.schedules_fk.route_fk.origin_fk.city}} To {{data.schedules_fk.route_fk.destination_fk.city}}
                                    </h3>


                                </td>
                                <td class="unit">{{s_cnt}}</td>
                                <td class="qty">Rs {{ data.schedules_fk.price }}</td>
                                <td class="total">Rs {{ data.total_price }}</td>



                            </tr>
                            




                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="1"></td>
                                <td colspan="2">SUBTOTAL</td>
                                <td>Rs {{ data.total_price }}</td>
                            </tr>
                            
                            <tr>
                                <td colspan="1"></td>
                                <td colspan="2">GRAND TOTAL</td>
                                <td>Rs {{data.total_price}}</td>
                            </tr>
                        </tfoot>
                    </table>
					<br>
                    <div class="thanks">Thank you!</div>
                    <div class="notices">
                        <div>DETAILS:</div>
                        <div class="notice">
                         	Booked Seat Number :
                            {% for i in seats %}
                            {{ i.seat_fk.seat_name }} , 
                            {% endfor %}
							<br>
                            Pickup Point: {{data.schedules_fk.route_fk.boarding_point}} <br>
							Dropping Point: {{data.schedules_fk.route_fk.dropping_point}}
                        </div>
                    </div>
                </main>
                <footer>
                    Invoice was created on a computer and is valid without the signature and seal.
                </footer>
            </div>
            <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
            <!-- <div></div> -->
        </div>
    </div>
</body>

</html>


templates/booking/razorpay.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}
{% if payment %}
<section class="parallax-window" data-parallax="scroll" data-image-src="{%static 'img/header_bg.jpg' %}"
    data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1 opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
        <div class="animated fadeInDown">
            <h1>Payment</h1>
            <p>Welcome to Pacific Tours & Travels</p>
        </div>
    </div>
</section>
<main>
    <div class="container margin_60" >

        <div class="main_title" >
            <div>
               <b> hello Dear Customer, please note that once you move back from this page your selected seat will be deleted and you need to select again for further bookings.</b>
            </div>
            <div style="margin-top: 300px;" class="container mx-auto text-center mt-4" v-if="name && amount">

                <form action="{% url 'booking:success' %}" method="POST">
                    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_susforIvG6nYky" //
                        Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                        data-amount="{{payment.amount}}" data-currency="INR" //You can accept international payments by
                        changing the currency code. Contact our Support Team to enable International for your account
                        data-order_id="{{ payment.id }}" //Replace with the order_id generated by you in the backend.
                        data-buttontext="Pay with Razorpay" data-name="Pacific Tours & Travels"
                        data-description="Thanks for The Booking." data-prefill.name="Patel Jay A"
                        data-prefill.email="jayp15813@gmail.com" data-prefill.contact="333333333"
                        data-theme.color="#F37254"></script>
                    <input type="hidden" custom="Hidden Element" name="hidden">
                </form>
            </div>
        </div>
    </div>
</main>
{% endif %}
{% endblock body %}

templates/booking/razorpay_stours.html
{% extends 'root/layout.html' %}
{% load static %}

{% block body %}
{% if payment %}
<section class="parallax-window" data-parallax="scroll" data-image-src="{%static 'img/header_bg.jpg' %}"
    data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1 opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
        <div class="animated fadeInDown">
            <h1>Payment</h1>
            <p>Welcome to Pacific Tours & Travels</p>
        </div>
    </div>
</section>
<main>
    <div class="container margin_60">

        <div class="main_title">
            <div>
                <b> hello Dear Customer, please note that once you move back from this page your selected seat will be deleted and you need to select again for further bookings.</b>
             </div>
            <div style="margin-top: 300px;" class="container mx-auto text-center mt-4" v-if="name && amount">

                <form action="{% url 'booking:success_stours' %}" method="POST">
                    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_susforIvG6nYky" //
                        Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                        data-amount="{{payment.amount}}" data-currency="INR" //You can accept international payments by
                        changing the currency code. Contact our Support Team to enable International for your account
                        data-order_id="{{ payment.id }}" //Replace with the order_id generated by you in the backend.
                        data-buttontext="Pay with Razorpay" data-name="Pacific Tours & Travels"
                        data-description="Thanks for The Booking." data-prefill.name="Patel Jay A"
                        data-prefill.email="jayp15813@gmail.com" data-prefill.contact="333333333"
                        data-theme.color="#F37254"></script>
                    <input type="hidden" custom="Hidden Element" name="hidden">
                </form>
            </div>
        </div>
    </div>
</main>
{% endif %}
{% endblock body %}